### ISSUE TITLE
Not working on Azure Function

### ISSUE THREAD

**Issue by bigmat** [Erol444/SeleniumProxyAuth#1]
Hello,
I have seen your nuget package and it looks exactly what I need.
I tested it in an Azure Function but it's not working. i got an error.
`Titanium.Web.Proxy: Could not load file or assembly 'Microsoft.Win32.Registry, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`

To reproduce :

- Create a new Azure Function with Visual Studio, v3 in .NetCore 3.1
- Install your package
- Instanciate the proxy

```
namespace FunctionApp1
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");
            var proxyServer = new SeleniumProxyServer(); // => throw here
            
            return new OkObjectResult("OK");
        }
    }
}
```

If you have any idea, it could help.
Thank you

**Comment by Erol444** [comment]
Hello @bigmat, I believe that the problem is your .net core version. This project is .net standard 2.0, meaning it should for .net core 2.0 projects. Check .net standard [specifications here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard). You should either compile this project as .net standard 2.1 or use .net core 2 for your project.

**Comment by bigmat** [comment]
I think it's more around the version 5.0 of the package Microsoft.Win32.Registry, because the pacakge 5.0.x are not compatible with Azure function right now.
For what you said about the framework version, that's not the issue because .netstandard 2.0 is compatible starting .NetCore 2.0 and higher. I managed to have you package working with a .NetCore 3.1 ConsoleApp.

Any thank you for the package ;)

**Comment by Erol444** [comment]
Oh, you are correct, my mistake. Then I have no idea what could go wrong with Azure functions since I have never used them, sorry:/

**Comment by bigmat** [comment]
It was an issue with Titanium.Web.Proxy version that targets .Net 5. I downgraded the package version and it's now working perfectly. Thank you
